### PR TITLE
Untitled

### PR DESCRIPTION
**Pull request by ghost**
- Changed agros.conf to display a Welcome message
- Changed main.c:
  - welcome_key
  - welcome_group
  - welcomeMessage

### CODE REVIEW

**Comment by joehakimrahme** [comment]
My first impressions:
- Do we really need to create a new Group in the conf file? Why not put it under general for the moment and we'll see later if it needs a separate group if the General group becomes too big
- Do we really need to call the group and the key  (welcome_group and welcome_key) through variables? Who is going to change those
- There's a blank space that looks ugly on the diff
- There should be a space before each opening parenthesis
- Why did you uncomment the syslog call?
- I really don't like the \n\n\n\n\n\t\t\t\t... We don't need it. I think.

**Comment by ghost** [comment]
1. Might be interesting to create a separate group for Messages from the conf file, and put Welcome in it... But a group for Welcome is a bit too much, I agree..
2. Fixed!
3. Don't know what happened to the syslog call (using vim, and not very used to it), but fixed it anyway
4. Fixed!

**Comment by ghost** [comment]
Damn, opening parentheses.. Let me fix that

**Comment by joehakimrahme** [comment]
Better. 

Some little problems with conventions:
- Don't use inline comments (//). I only use /\* ... */ (Stupid choice I know). 
- Commit sentences must always start with a third-person verb (Fixes, Updates, enhances, corrects, ...). I'll update the AAC. 

And last but not least, a real issue:
- Welcome message should be optional. If I comment the line in agros.conf, I'd like it to act as nothing happened. Right now it outputs a very ugly _(null)_ message.

**Pull request closed without merging**
